Models/BotType.cs
namespace RpvStartBotService.Models
{
    public enum BotType
    {
        Telegram,
        TelegramAdmin,
        TelegramStaff,
        Vk        
    }
}

Models/ErrorViewModel.cs
using System;

namespace RpvStartBotService.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FolderOptions.cs
namespace RpvStartBotService.Models
{
    public class FolderOptions
    {
        public string InputTelegramFolder { get; set; }
        public string InputVkFolder { get; set; }
        public string OutputFolder { get; set; }
        public string InputTelegramAdminFolder { get; set; }
    }
}

Models/InputOptionsModel.cs
using System.Collections.Generic;
using System.Linq;

namespace RpvStartBotService.Models
{
    public class InputOptionsModel
    {
        public InputOptionsModel()
        {

        }
        public InputOptionsModel(int vkcount = 1, int tlgcount = 1, int tlgAdmincount = 1)
        {
            var items = Enumerable.Repeat("", vkcount);
            var longItems = Enumerable.Repeat(default(long), vkcount);
            var itemsTlg = Enumerable.Repeat("", tlgcount);
            var itemsAdTlg = Enumerable.Repeat("", tlgAdmincount);

            VkToken = new List<string>(items);
            GroupID = new List<long>(longItems);
            Currency = new List<string>(items);

            TelegramToken = new List<string>(itemsAdTlg);
            TelegramAdminToken = new List<string>(itemsAdTlg);
            ClientTelegramToken = new List<string>(itemsTlg);
        }
        public string BaseApiAddress { get; set; } = "http://localhost:21021/";
       
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public string Tenant { get; set; } 

        public List<string> ClientTelegramToken { get; set; }


        public List<string> TelegramToken { get; set; }
        public List<string> TelegramAdminToken { get; set; }


        public List<string> VkToken { get; set; }
        public List<long> GroupID { get; set; }
        public List<string> Currency { get; set; }

    }
}

Models/ServiceModel.cs
using System.ServiceProcess;

namespace RpvStartBotService.Models
{
    public class ServiceModel
    {
        public string ServiceName { get; set; }
        public string DisplayName {get;set;}
        public ServiceControllerStatus Status { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RpvStartBotService.Models;
using RpvStartBotService.Services;

namespace RpvStartBotService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IBotServiceManagement _botService;               

        public HomeController(ILogger<HomeController> logger, IBotServiceManagement botService)
        {
            _logger = logger;            
            _botService = botService;
        }

        public async Task<IActionResult> Index()
        {
            var vkCount = await _botService.GetUniqueBotPropertieCount(BotType.Vk);
            var tlgCount = await _botService.GetUniqueBotPropertieCount(BotType.Telegram);
            var tlgAdCount = await _botService.GetUniqueBotPropertieCount(BotType.TelegramAdmin);

            var model = new InputOptionsModel(vkCount, tlgCount, tlgAdCount);
            return View(model);
        }  

        [HttpPost]
        public async Task<IActionResult> Action(InputOptionsModel model)
        {
            await _botService.CreateAndRunServices(model);            
            
            return Redirect("/Service/Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using RpvStartBotService.Services;
using System;
using System.Linq;

namespace RpvStartBotService.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IBotServiceManagement _botService;

        public ServiceController(IBotServiceManagement botService)
        {
            _botService = botService;
        }
        public IActionResult Index()
        {
            var services = _botService.GetServices();            
            return View(services);
        }
        public IActionResult IndexPartial()
        {
            var services = _botService.GetServices();
            return PartialView("_ServicePartial", services);
        }

        [HttpPost]
        public IActionResult ChangeState([FromBody]string serviceName)
        {
            var result = _botService.ChangeStateOfService(serviceName);
            return Ok(result);
        }

        [HttpPost]
        public IActionResult DeleteService([FromBody]string serviceName)
        {
            _botService.DeleteService(serviceName);
            return Ok();
        }
    }
}

Views/Home/Index.cshtml
@model InputOptionsModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">    
    <form method="post" asp-action="Action">
        <h4>Основные настройки</h4>
        <div class="form-group">
            @Html.LabelFor(x => x.BaseApiAddress)
            @Html.TextBoxFor(x => x.BaseApiAddress, new { @class = "form-control form-control-sm" })

            @Html.LabelFor(x => x.UserLogin)
            @Html.TextBoxFor(x => x.UserLogin, new { @class = "form-control form-control-sm" })

            @Html.LabelFor(x => x.UserPassword)
            @Html.TextBoxFor(x => x.UserPassword, new { @class = "form-control form-control-sm" })

            @Html.LabelFor(x => x.Tenant)
            @Html.TextBoxFor(x => x.Tenant, new { @class = "form-control form-control-sm" })

            <h4>Telegram - Админ - настройки</h4>

            @Html.LabelFor(x => x.TelegramToken)
            @for (int i = 0; i < Model.TelegramToken.Count; i++)
            {
                @Html.TextBoxFor(x => x.TelegramToken[i], new { @class = "form-control form-control-sm" })
            }

            @Html.LabelFor(x => x.TelegramAdminToken)
            @for (int i = 0; i < Model.TelegramAdminToken.Count; i++)
            {
                @Html.TextBoxFor(x => x.TelegramAdminToken[i], new { @class = "form-control form-control-sm" })
            }

            <h4>Telegram - Клиент - настройки</h4>

            @Html.LabelFor(x => x.ClientTelegramToken)
            @for(int i = 0; i< Model.ClientTelegramToken.Count; i++)
            {
                @Html.TextBoxFor(x => x.ClientTelegramToken[i], new { @class = "form-control form-control-sm" })
            }

            <h4>Vk-настройки</h4>

            @Html.LabelFor(x => x.VkToken)
            @for (int i = 0; i < Model.VkToken.Count; i++)
            {
                @Html.TextBoxFor(x => x.VkToken[i], new { @class = "form-control form-control-sm" })
            }

            @Html.LabelFor(x => x.GroupID)
            @for (int i = 0; i < Model.GroupID.Count; i++)
            {
                @Html.TextBoxFor(x => x.GroupID[i], new { @class = "form-control form-control-sm" })
            }

            @Html.LabelFor(x => x.Currency)
            @for (int i = 0; i < Model.Currency.Count; i++)
            {
                @Html.TextBoxFor(x => x.Currency[i], new { @class = "form-control form-control-sm" })
            }

        </div>
        <input type="submit" value="Добавить" class="btn btn-primary" />
    </form>
</div>

Views/Service/Index.cshtml
@model IEnumerable<RpvStartBotService.Models.ServiceModel>

@{
    ViewData["Title"] = "Службы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="serviceResult">
    @await Html.PartialAsync("_ServicePartial", Model)
</div>

Views/Service/_ServicePartial.cshtml
@model IEnumerable<RpvStartBotService.Models.ServiceModel>

<table class="table table-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ServiceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisplayName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                Действие
            </th>
            <th>
                Удаление
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="item_@item.ServiceName">
                <td>
                    @Html.DisplayFor(modelItem => item.ServiceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayName)
                </td>
                <td id="@item.ServiceName">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @if (item.Status == System.ServiceProcess.ServiceControllerStatus.Running)
                    {
                        <a href="#" class="stateLink">Остановить</a>
                    }
                    else if (item.Status == System.ServiceProcess.ServiceControllerStatus.Stopped)
                    { 
                        <a href="#" class="stateLink">Запустить</a>
                    }

                </td>
                <td>
                    <a href="#" class="removeLink">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RpvStartBotService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RpvStartBotService</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Service" asp-action="Index">Службы</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RpvStartBotService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>